Numpy_ ---> data Analysis 

In [1]:
import numpy as np 

In [2]:
#array 
arr = np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
# built in method : genarated data
z_arr = np.zeros((3,5))
z_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
o_array = np.ones((2,2))
o_array

array([[1., 1.],
       [1., 1.]])

In [6]:
n_array = np.arange(0,10,2)
n_array

array([0, 2, 4, 6, 8])

In [7]:
f_array = np.full((2,5),3)
f_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [9]:
l_array = np.linspace(0,3,5)
l_array

array([0.  , 0.75, 1.5 , 2.25, 3.  ])

In [10]:
#random 
arra2 = np.random.rand(5)
arra2

array([0.26044847, 0.59762454, 0.02897366, 0.01058975, 0.62487955])

In [11]:
arra3 = np.random.rand(5,6)
arra3

array([[0.08539805, 0.06670939, 0.84459429, 0.36707792, 0.53995443,
        0.41677176],
       [0.49051623, 0.67137035, 0.31234461, 0.19279483, 0.3000666 ,
        0.73589728],
       [0.15237579, 0.6909716 , 0.60414969, 0.72128963, 0.93232266,
        0.4982541 ],
       [0.30114747, 0.49980992, 0.94971984, 0.93042446, 0.61663089,
        0.91656008],
       [0.95347252, 0.48853479, 0.80148476, 0.1758617 , 0.13611801,
        0.41137364]])

In [12]:
arra2 = np.random.randint(1,12)
arra2

6

In [13]:
arra2 = np.random.randint(1,12,5)
arra2

array([ 6,  3,  3, 10,  3])

In [14]:
#identify matrix 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
arr.shape

(7,)

In [17]:
arr.size

7

In [18]:
arr.dtype

dtype('int64')

-----

In [19]:
arr1 = np.arange(25)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
arr1.reshape(5,5) # take into account the size of matrix 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
arr3=np.array([1,7,8,9,5])

In [25]:
arr3

array([1, 7, 8, 9, 5])

In [26]:
arr3.min()

1

In [27]:
arr3.max()

9

In [28]:
arr3.argmin() # index

0

In [29]:
arr3.argmax()

3

-----------

Array = 1D -------> vector 


Array = 2D -------> matrix 


Array = 3D -------> tensor 


axis -----> row = 0 , column = 1

In [31]:
# data type 

arry4 = np.array([1,34,5,6,7,8,8],dtype=np.float32)
arry4

array([ 1., 34.,  5.,  6.,  7.,  8.,  8.], dtype=float32)

In [32]:
arry5 = np.array([True,50]) # convert into int
arry5

array([ 1, 50])

In [33]:
arry5.dtype

dtype('int64')

In [34]:
arry55 = np.array([True,50,2.5])
arry55

array([ 1. , 50. ,  2.5])

In [35]:
arry55.dtype

dtype('float64')

------

In [44]:
arry8 = np.array([1,34,5,6,7,8,3,4,5])
arry8[1]

34

In [45]:
arry88 = arry8.reshape(3,3)
arry88

array([[ 1, 34,  5],
       [ 6,  7,  8],
       [ 3,  4,  5]])

In [46]:
arry88.shape

(3, 3)

In [47]:
arry88[0] # row

array([ 1, 34,  5])

In [48]:
arry88[0][0] #row and colum

1

In [49]:
arry88[:,0]

array([1, 6, 3])

In [51]:
arry88[1:3]

array([[6, 7, 8],
       [3, 4, 5]])

In [52]:
arry88[1:3,0:3]

array([[6, 7, 8],
       [3, 4, 5]])

-----

In [53]:
arr = np.arange(1,100)
aee2 = arr.reshape(3,33)
aee2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33],
       [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
        50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66],
       [67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
        83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
        99]])

In [54]:
aee2[:,1:12:2]

array([[ 2,  4,  6,  8, 10, 12],
       [35, 37, 39, 41, 43, 45],
       [68, 70, 72, 74, 76, 78]])

--------

In [56]:
# broadcast 
arr = np.arange(25)
sliced_Arr = arr[0:10] # view
print(arr)
print(sliced_Arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[0 1 2 3 4 5 6 7 8 9]


In [57]:
sliced_Arr[:] = 100

In [58]:
print(sliced_Arr)

[100 100 100 100 100 100 100 100 100 100]


In [59]:
print(arr)

[100 100 100 100 100 100 100 100 100 100  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24]


In [ ]:
#cope of the array

In [60]:
arr = np.arange(25)
sliced_Arr = arr[0:10].copy()
print(arr)
print(sliced_Arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[0 1 2 3 4 5 6 7 8 9]


Sort of the array 

In [62]:
np.sort(arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [63]:
np.sort(arr,axis=0)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

------------

In [64]:
# filter of array 

In [67]:
arr = np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [68]:
mask = arr%2 == 0
mask

array([False,  True, False,  True, False])

In [69]:
arr[mask]

array([2, 4])

In [71]:
np.where(arr%2==0,'',arr)

array(['1', '', '3', '', '5'], dtype='<U21')

---------------

In [74]:
# array operation 
arr = np.array([2,4,5,6,7,8,9,0,9])
arr3 = np.array([2,4,3,4,5,6,7,0,9])
arr - arr3

array([0, 0, 2, 2, 2, 2, 2, 0, 0])

In [75]:
arr + arr3

array([ 4,  8,  8, 10, 12, 14, 16,  0, 18])

In [76]:
arr * arr3

array([ 4, 16, 15, 24, 35, 48, 63,  0, 81])

In [ ]:
np.